### ISSUE TITLE
Only for discussion about Debug on Windows

### ISSUE THREAD

**Issue by BDisp** [snapsinazfs/snapsinazfs#25]
https://github.com/gui-cs/Terminal.Gui/issues/2775#issuecomment-1663027676

Yes you are right, I using Debug mode and I followed all the conditional compiler code to make it work :-)
On VSCode I didn't create any task or launch json file. I only used the c# tool kit to build. The solution builds with the correct configuration but building the project it create wrong configuration. But don0t bother with this, it was only to realize the fact. Thanks.

**Comment by dodexahedron** [comment]
I'm making some modifications for 1.1 anyway, partially because of wanting to make things more testable.

It will also result in slightly faster start-up of the configuration console, since I moved that code path to a more sensible place, before the service gets set up, which is unnecessary if launching the configuration console.

A much earlier alpha version of the application used to explicitly check and validate the configuration files. I changed the way configuration works, though, when I decided to make a large break from how the application this was inspired by works, and I never re-implemented validation. I should probably put some simple form of validation back in, anyway, even if just to provide more user-friendly output for situations, including but not just limited to this one, where the configuration files aren't where they're expected to be or in the format they're expected to be in.

I already have plans to add a command line argument to override the location the configuration file is loaded from, so I will probably do that work in whatever feature branch gets created for that, when I get to it.

**Comment by BDisp** [comment]
How about using cmake? It's great for cross platforms.

**Comment by dodexahedron** [comment]
Well, the application is only useful on Linux, since ZFS is a Linux thing, so there's just not much point in me learning another build toolset. Windows compatibility is really only for my own convenience, since I prefer to work in Visual Studio with ReSharper. 😁

And automake or gnu make are usually installed on most Linux machines anyway, and the Makefile provides the standard `make ; make install` pattern that most projects use. Outside of development/debugging, there's basically no reason to build or use it any other way, so it just isn't really worth taking time away from working on the application itself, in my opinion. The biggest thing I might do is finish learning some basics of autoconf, so I can provide a standard `./configure` script, to handle pre-filling correct values for directories in the Makefile, for systems that don't match the test environments.

I _may_ provide recipes in the Makefile for the rest of the configurations, once I'm done with some major features I want to implement, but they don't have practical general uses, anyway (outside of development, that is). In fact, you already _can_ use the other build configurations, with the Makefile, if you override the appropriate environment variables, as it doesn't actually hard-code the build configurations into any invocations of `dotnet`. (It does for the publish profile - but not the build configuration - for `make publish-release`, but I just noticed that when checking myself for this comment, and will fix it for RC4).

The variables that the Makefile uses are all at the top of the Makefile, and a couple of them are even mentioned in the new install help (can be viewed by running `make help`). I consider that an "advanced" topic and out of scope for what I intend to explicitly support, so it isn't documented in detail, but users who understand how `make` works should be able to grok it pretty quickly.

I'll be pushing the Makefile change to `master` pretty soon that both makes sure all configurations are set by variables (and thus can be overridden) and also adds several more variables for even more control and mostly to help avoid errors in future modifications to the Makefile.

**Comment by dodexahedron** [comment]
I'm also implementing #12 for version 1.0, now, which will provide a permanent and flexible solution to the configuration load issues you ran into. I should be done with that pretty soon.

**Comment by dodexahedron** [comment]
#12 is finished and I'll be preparing RC4 in a few minutes.

The default behavior without the --config option specified should be sufficient for most cases, on both linux and windows, and allows config files in the same folder to be used. Otherwise, explicit configuration files can be specified with the `--config` option to override configuration loading. All files are marked optional, so missing files won't cause an exception.

**Comment by dodexahedron** [comment]
RC4 is released.

This fixes the config load errors in all configurations, and allows it to be overridden, if necessary in any environment.

Closing this one.

Feel free to comment further if you continue to have trouble.
